# Generated by Django 5.2.8 on 2025-11-20 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('capacity', models.PositiveIntegerField(default=0)),
                ('professor', models.CharField(max_length=150)),
                ('day', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=100)),
                ('min_units', models.PositiveIntegerField(default=1)),
                ('max_units', models.PositiveIntegerField(default=3)),
                ('prerequisites', models.ManyToManyField(blank=True, to='courses.course')),
            ],
        ),
    ]
