# Generated by Django 5.2.8 on 2025-11-28 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='max_units',
        ),
        migrations.RemoveField(
            model_name='course',
            name='min_units',
        ),
        migrations.AddField(
            model_name='course',
            name='units',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
