# Generated by Django 5.2.8 on 2025-11-29 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_course_max_units_remove_course_min_units_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='day',
            field=models.CharField(max_length=100),
        ),
    ]
